// Generated by CoffeeScript 1.10.0
var Scene;

Scene = {
  write: function(char, text) {
    Visuals.textBox.reset();
    Visuals.textBox.visible = true;
    Visuals.textBox.text = text;
    if (!Visuals.textBox.write) {
      generate.timer("startWriting", setting.textBox.loadPause, (function() {
        return generate.timer("writing", setting.textBox.letterPause, (function() {
          if (!Visuals.textBox.type()) {
            return Timers.remove("writing");
          }
        }), true);
      }));
    }
    return Visuals.faces[char].visible = true;
  },
  s1: function() {
    this.write(0, "HELLO WORLD.");
    return this.wait();
  }
};
