// Generated by CoffeeScript 1.10.0
var context, format, generate, menu, menubg, onKeyDown;

menubg = new Raster("menubg");

menubg.position = view.center;

format = {
  menu: {
    xpos: 620,
    xSelectOffset: 30,
    ypos: 240,
    yint: 20,
    textColor: 'black',
    fontFamily: '"Palatino Linotype", "Book Antiqua", Palatino, serif',
    justification: 'right',
    fontSize: 20
  }
};

generate = {
  menuText: function(yoffset, content) {
    var preselect, xpos;
    xpos = format.menu.xpos;
    preselect = yoffset === menu.cursor;
    if (preselect) {
      xpos -= format.menu.xSelectOffset;
    }
    return new PointText({
      position: [xpos, format.menu.ypos + yoffset * format.menu.yint],
      fontFamily: format.menu.fontFamily,
      justification: format.menu.justification,
      fontSize: format.menu.fontSize,
      textColor: format.menu.textColor,
      content: content
    });
  }
};

menu = {
  cursor: 1
};

menu.m_new = generate.menuText(0, "NEW");

menu.m_continue = generate.menuText(1, "CONTINUE");

menu.m_load = generate.menuText(2, "LOAD FROM FILE");

menu.m_export = generate.menuText(3, "SAVE TO FILE");

menu.m_settings = generate.menuText(4, "SETTINGS");

menu.m_sandbox = generate.menuText(5, "SANDBOX");

menu.options = [menu.m_new, menu.m_continue, menu.m_load, menu.m_export, menu.m_settings, menu.m_sandbox];

context = menu;

onKeyDown = function(event) {
  if (context === menu) {
    if (event.key === 'down' || event.key === 'up') {
      console.log("Moved menu cursor " + event.key);
      menu.options[menu.cursor].position.x += format.menu.xSelectOffset;
      if (event.key === 'down') {
        menu.cursor++;
      } else {
        menu.cursor--;
      }
      if (menu.cursor >= menu.options.length) {
        menu.cursor %= menu.options.length;
      }
      return menu.options[menu.cursor].position.x -= format.menu.xSelectOffset;
    }
  }
};
