// Generated by CoffeeScript 1.10.0

/*

// Create a Paper.js Path to draw a line into it:
	var path = new Path();
	// Give the stroke a color
	path.strokeColor = 'black';
	var start = new Point(100, 100);
	// Move to start and draw a line from there
	path.moveTo(start);
	// Note the plus operator on Point objects.
	// PaperScript does that for us, and much more!
	path.lineTo(start + [ 100, -50 ]);
 */
window.onload = function() {
  var path, start;
  path = new paper.Path();
  path.strokeColor = 'black';
  start = new paper.Point(100, 100);
  path.moveTo(start);
  return path.lineTo(start + [100, -50]);
};
